//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WOSApi.WOSSearch {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WokSearchServiceSoapBinding", Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class WokSearchService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback citedReferencesRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback relatedRecordsOperationCompleted;
        
        private System.Threading.SendOrPostCallback citedReferencesOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchOperationCompleted;
        
        private System.Threading.SendOrPostCallback citingArticlesOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrieveByIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WokSearchService() {
            this.Url = global::WOSApi.Properties.Settings.Default.WOSApi_WOSSearch_WokSearchService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event citedReferencesRetrieveCompletedEventHandler citedReferencesRetrieveCompleted;
        
        /// <remarks/>
        public event relatedRecordsCompletedEventHandler relatedRecordsCompleted;
        
        /// <remarks/>
        public event citedReferencesCompletedEventHandler citedReferencesCompleted;
        
        /// <remarks/>
        public event retrieveCompletedEventHandler retrieveCompleted;
        
        /// <remarks/>
        public event searchCompletedEventHandler searchCompleted;
        
        /// <remarks/>
        public event citingArticlesCompletedEventHandler citingArticlesCompleted;
        
        /// <remarks/>
        public event retrieveByIdCompletedEventHandler retrieveByIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", ResponseNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public citedReference[] citedReferencesRetrieve([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string queryId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] retrieveParameters retrieveParameters) {
            object[] results = this.Invoke("citedReferencesRetrieve", new object[] {
                        queryId,
                        retrieveParameters});
            return ((citedReference[])(results[0]));
        }
        
        /// <remarks/>
        public void citedReferencesRetrieveAsync(string queryId, retrieveParameters retrieveParameters) {
            this.citedReferencesRetrieveAsync(queryId, retrieveParameters, null);
        }
        
        /// <remarks/>
        public void citedReferencesRetrieveAsync(string queryId, retrieveParameters retrieveParameters, object userState) {
            if ((this.citedReferencesRetrieveOperationCompleted == null)) {
                this.citedReferencesRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OncitedReferencesRetrieveOperationCompleted);
            }
            this.InvokeAsync("citedReferencesRetrieve", new object[] {
                        queryId,
                        retrieveParameters}, this.citedReferencesRetrieveOperationCompleted, userState);
        }
        
        private void OncitedReferencesRetrieveOperationCompleted(object arg) {
            if ((this.citedReferencesRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.citedReferencesRetrieveCompleted(this, new citedReferencesRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", ResponseNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fullRecordSearchResults relatedRecords([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string databaseId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uid, [System.Xml.Serialization.XmlElementAttribute("editions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] editionDesc[] editions, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] timeSpan timeSpan, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string queryLanguage, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] retrieveParameters retrieveParameters) {
            object[] results = this.Invoke("relatedRecords", new object[] {
                        databaseId,
                        uid,
                        editions,
                        timeSpan,
                        queryLanguage,
                        retrieveParameters});
            return ((fullRecordSearchResults)(results[0]));
        }
        
        /// <remarks/>
        public void relatedRecordsAsync(string databaseId, string uid, editionDesc[] editions, timeSpan timeSpan, string queryLanguage, retrieveParameters retrieveParameters) {
            this.relatedRecordsAsync(databaseId, uid, editions, timeSpan, queryLanguage, retrieveParameters, null);
        }
        
        /// <remarks/>
        public void relatedRecordsAsync(string databaseId, string uid, editionDesc[] editions, timeSpan timeSpan, string queryLanguage, retrieveParameters retrieveParameters, object userState) {
            if ((this.relatedRecordsOperationCompleted == null)) {
                this.relatedRecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrelatedRecordsOperationCompleted);
            }
            this.InvokeAsync("relatedRecords", new object[] {
                        databaseId,
                        uid,
                        editions,
                        timeSpan,
                        queryLanguage,
                        retrieveParameters}, this.relatedRecordsOperationCompleted, userState);
        }
        
        private void OnrelatedRecordsOperationCompleted(object arg) {
            if ((this.relatedRecordsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.relatedRecordsCompleted(this, new relatedRecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", ResponseNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public citedReferencesSearchResults citedReferences([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string databaseId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string queryLanguage, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] retrieveParameters retrieveParameters) {
            object[] results = this.Invoke("citedReferences", new object[] {
                        databaseId,
                        uid,
                        queryLanguage,
                        retrieveParameters});
            return ((citedReferencesSearchResults)(results[0]));
        }
        
        /// <remarks/>
        public void citedReferencesAsync(string databaseId, string uid, string queryLanguage, retrieveParameters retrieveParameters) {
            this.citedReferencesAsync(databaseId, uid, queryLanguage, retrieveParameters, null);
        }
        
        /// <remarks/>
        public void citedReferencesAsync(string databaseId, string uid, string queryLanguage, retrieveParameters retrieveParameters, object userState) {
            if ((this.citedReferencesOperationCompleted == null)) {
                this.citedReferencesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncitedReferencesOperationCompleted);
            }
            this.InvokeAsync("citedReferences", new object[] {
                        databaseId,
                        uid,
                        queryLanguage,
                        retrieveParameters}, this.citedReferencesOperationCompleted, userState);
        }
        
        private void OncitedReferencesOperationCompleted(object arg) {
            if ((this.citedReferencesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.citedReferencesCompleted(this, new citedReferencesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", ResponseNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fullRecordData retrieve([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string queryId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] retrieveParameters retrieveParameters) {
            object[] results = this.Invoke("retrieve", new object[] {
                        queryId,
                        retrieveParameters});
            return ((fullRecordData)(results[0]));
        }
        
        /// <remarks/>
        public void retrieveAsync(string queryId, retrieveParameters retrieveParameters) {
            this.retrieveAsync(queryId, retrieveParameters, null);
        }
        
        /// <remarks/>
        public void retrieveAsync(string queryId, retrieveParameters retrieveParameters, object userState) {
            if ((this.retrieveOperationCompleted == null)) {
                this.retrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrieveOperationCompleted);
            }
            this.InvokeAsync("retrieve", new object[] {
                        queryId,
                        retrieveParameters}, this.retrieveOperationCompleted, userState);
        }
        
        private void OnretrieveOperationCompleted(object arg) {
            if ((this.retrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrieveCompleted(this, new retrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", ResponseNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fullRecordSearchResults search([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] queryParameters queryParameters, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] retrieveParameters retrieveParameters) {
            object[] results = this.Invoke("search", new object[] {
                        queryParameters,
                        retrieveParameters});
            return ((fullRecordSearchResults)(results[0]));
        }
        
        /// <remarks/>
        public void searchAsync(queryParameters queryParameters, retrieveParameters retrieveParameters) {
            this.searchAsync(queryParameters, retrieveParameters, null);
        }
        
        /// <remarks/>
        public void searchAsync(queryParameters queryParameters, retrieveParameters retrieveParameters, object userState) {
            if ((this.searchOperationCompleted == null)) {
                this.searchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchOperationCompleted);
            }
            this.InvokeAsync("search", new object[] {
                        queryParameters,
                        retrieveParameters}, this.searchOperationCompleted, userState);
        }
        
        private void OnsearchOperationCompleted(object arg) {
            if ((this.searchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchCompleted(this, new searchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", ResponseNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fullRecordSearchResults citingArticles([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string databaseId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uid, [System.Xml.Serialization.XmlElementAttribute("editions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] editionDesc[] editions, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] timeSpan timeSpan, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string queryLanguage, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] retrieveParameters retrieveParameters) {
            object[] results = this.Invoke("citingArticles", new object[] {
                        databaseId,
                        uid,
                        editions,
                        timeSpan,
                        queryLanguage,
                        retrieveParameters});
            return ((fullRecordSearchResults)(results[0]));
        }
        
        /// <remarks/>
        public void citingArticlesAsync(string databaseId, string uid, editionDesc[] editions, timeSpan timeSpan, string queryLanguage, retrieveParameters retrieveParameters) {
            this.citingArticlesAsync(databaseId, uid, editions, timeSpan, queryLanguage, retrieveParameters, null);
        }
        
        /// <remarks/>
        public void citingArticlesAsync(string databaseId, string uid, editionDesc[] editions, timeSpan timeSpan, string queryLanguage, retrieveParameters retrieveParameters, object userState) {
            if ((this.citingArticlesOperationCompleted == null)) {
                this.citingArticlesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncitingArticlesOperationCompleted);
            }
            this.InvokeAsync("citingArticles", new object[] {
                        databaseId,
                        uid,
                        editions,
                        timeSpan,
                        queryLanguage,
                        retrieveParameters}, this.citingArticlesOperationCompleted, userState);
        }
        
        private void OncitingArticlesOperationCompleted(object arg) {
            if ((this.citingArticlesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.citingArticlesCompleted(this, new citingArticlesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", ResponseNamespace="http://woksearch.v3.wokmws.thomsonreuters.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fullRecordSearchResults retrieveById([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string databaseId, [System.Xml.Serialization.XmlElementAttribute("uid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] uid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string queryLanguage, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] retrieveParameters retrieveParameters) {
            object[] results = this.Invoke("retrieveById", new object[] {
                        databaseId,
                        uid,
                        queryLanguage,
                        retrieveParameters});
            return ((fullRecordSearchResults)(results[0]));
        }
        
        /// <remarks/>
        public void retrieveByIdAsync(string databaseId, string[] uid, string queryLanguage, retrieveParameters retrieveParameters) {
            this.retrieveByIdAsync(databaseId, uid, queryLanguage, retrieveParameters, null);
        }
        
        /// <remarks/>
        public void retrieveByIdAsync(string databaseId, string[] uid, string queryLanguage, retrieveParameters retrieveParameters, object userState) {
            if ((this.retrieveByIdOperationCompleted == null)) {
                this.retrieveByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrieveByIdOperationCompleted);
            }
            this.InvokeAsync("retrieveById", new object[] {
                        databaseId,
                        uid,
                        queryLanguage,
                        retrieveParameters}, this.retrieveByIdOperationCompleted, userState);
        }
        
        private void OnretrieveByIdOperationCompleted(object arg) {
            if ((this.retrieveByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrieveByIdCompleted(this, new retrieveByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class retrieveParameters {
        
        private int firstRecordField;
        
        private int countField;
        
        private sortField[] sortFieldField;
        
        private viewField[] viewFieldField;
        
        private keyValuePair[] optionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int firstRecord {
            get {
                return this.firstRecordField;
            }
            set {
                this.firstRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sortField", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sortField[] sortField {
            get {
                return this.sortFieldField;
            }
            set {
                this.sortFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("viewField", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public viewField[] viewField {
            get {
                return this.viewFieldField;
            }
            set {
                this.viewFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("option", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class sortField {
        
        private string nameField;
        
        private string sortField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sort {
            get {
                return this.sortField1;
            }
            set {
                this.sortField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class queryParameters {
        
        private string databaseIdField;
        
        private string userQueryField;
        
        private editionDesc[] editionsField;
        
        private string symbolicTimeSpanField;
        
        private timeSpan timeSpanField;
        
        private string queryLanguageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string databaseId {
            get {
                return this.databaseIdField;
            }
            set {
                this.databaseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userQuery {
            get {
                return this.userQueryField;
            }
            set {
                this.userQueryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("editions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public editionDesc[] editions {
            get {
                return this.editionsField;
            }
            set {
                this.editionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string symbolicTimeSpan {
            get {
                return this.symbolicTimeSpanField;
            }
            set {
                this.symbolicTimeSpanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public timeSpan timeSpan {
            get {
                return this.timeSpanField;
            }
            set {
                this.timeSpanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryLanguage {
            get {
                return this.queryLanguageField;
            }
            set {
                this.queryLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class editionDesc {
        
        private string collectionField;
        
        private string editionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string collection {
            get {
                return this.collectionField;
            }
            set {
                this.collectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string edition {
            get {
                return this.editionField;
            }
            set {
                this.editionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class timeSpan {
        
        private string beginField;
        
        private string endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class fullRecordData {
        
        private labelValuesPair[] optionValueField;
        
        private string recordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optionValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public labelValuesPair[] optionValue {
            get {
                return this.optionValueField;
            }
            set {
                this.optionValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class labelValuesPair {
        
        private string labelField;
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class citedReferencesSearchResults {
        
        private string queryIdField;
        
        private citedReference[] referencesField;
        
        private int recordsFoundField;
        
        private long recordsSearchedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("references", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public citedReference[] references {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int recordsFound {
            get {
                return this.recordsFoundField;
            }
            set {
                this.recordsFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long recordsSearched {
            get {
                return this.recordsSearchedField;
            }
            set {
                this.recordsSearchedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class citedReference {
        
        private string uidField;
        
        private string docidField;
        
        private string articleIdField;
        
        private string citedAuthorField;
        
        private string timesCitedField;
        
        private string yearField;
        
        private string pageField;
        
        private string volumeField;
        
        private string citedTitleField;
        
        private string citedWorkField;
        
        private string hotField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string docid {
            get {
                return this.docidField;
            }
            set {
                this.docidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string articleId {
            get {
                return this.articleIdField;
            }
            set {
                this.articleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string citedAuthor {
            get {
                return this.citedAuthorField;
            }
            set {
                this.citedAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timesCited {
            get {
                return this.timesCitedField;
            }
            set {
                this.timesCitedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string citedTitle {
            get {
                return this.citedTitleField;
            }
            set {
                this.citedTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string citedWork {
            get {
                return this.citedWorkField;
            }
            set {
                this.citedWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hot {
            get {
                return this.hotField;
            }
            set {
                this.hotField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class fullRecordSearchResults {
        
        private string queryIdField;
        
        private int recordsFoundField;
        
        private long recordsSearchedField;
        
        private string parentField;
        
        private labelValuesPair[] optionValueField;
        
        private string recordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int recordsFound {
            get {
                return this.recordsFoundField;
            }
            set {
                this.recordsFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long recordsSearched {
            get {
                return this.recordsSearchedField;
            }
            set {
                this.recordsSearchedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optionValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public labelValuesPair[] optionValue {
            get {
                return this.optionValueField;
            }
            set {
                this.optionValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class keyValuePair {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.v3.wokmws.thomsonreuters.com")]
    public partial class viewField {
        
        private string collectionNameField;
        
        private string[] fieldNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string collectionName {
            get {
                return this.collectionNameField;
            }
            set {
                this.collectionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fieldName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] fieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void citedReferencesRetrieveCompletedEventHandler(object sender, citedReferencesRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class citedReferencesRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal citedReferencesRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public citedReference[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((citedReference[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void relatedRecordsCompletedEventHandler(object sender, relatedRecordsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class relatedRecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal relatedRecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fullRecordSearchResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fullRecordSearchResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void citedReferencesCompletedEventHandler(object sender, citedReferencesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class citedReferencesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal citedReferencesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public citedReferencesSearchResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((citedReferencesSearchResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void retrieveCompletedEventHandler(object sender, retrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fullRecordData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fullRecordData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void searchCompletedEventHandler(object sender, searchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fullRecordSearchResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fullRecordSearchResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void citingArticlesCompletedEventHandler(object sender, citingArticlesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class citingArticlesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal citingArticlesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fullRecordSearchResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fullRecordSearchResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void retrieveByIdCompletedEventHandler(object sender, retrieveByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrieveByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrieveByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fullRecordSearchResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fullRecordSearchResults)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591